### ISSUE TITLE
[BUG] Task fails if `base` build fails

### ISSUE THREAD

**Issue by TheSonOfThomp** [preactjs/compressed-size-action#100] opened 2023-10-03 01:10 UTC
If the `base` build fails then the task fails, regardless of whether the `current` branch build is successful.

I would expect this to pass if the `[current]` build is valid, or at least provide an option to bypass this

**Comment by rschristian** [comment] 2023-12-20 15:06
> I would expect this to pass if the [current] build is valid, or at least provide an option to bypass this

How would that work? Without a base to compare to what would this action be doing?

**Comment by TheSonOfThomp** [comment] 2023-12-23 20:48
Assume the base build is broken, and we've opened a PR to fix this.
For any PR into main, we require a check for file sizes before the branch is able to be merged.
However, since the base branch is failing, this check fails, and we're prevented from merging or PR into main.

I would expect that if the base branch is failing to build, then this action would pass (since whatever file size in our current branch is better than no files in the main branch)

**Comment by rschristian** [comment] 2023-12-24 11:55
> Assume the base build is broken, and we've opened a PR to fix this.
> For any PR into main, we require a check for file sizes before the branch is able to be merged.
> However, since the base branch is failing, this check fails, and we're prevented from merging or PR into main.

Then you need to circumvent your merge restrictions.

> I would expect that if the base branch is failing to build, then this action would pass (since whatever file size in our current branch is better than no files in the main branch)

Sorry, but I disagree with this. A failure to build should not result in a green light to merge. There's clearly problems that need to be addressed which is signaled by the failing action.

Going to close this out, working as intended. I get this might cause a problem like in the situation you outlined, but the correct fix is to address that in your repo, not in the action. Doing so would be *extremely* permissive.

**Closed by rschristian** 2023-12-24 11:55 UTC
